### ISSUE TITLE
Ripgrep

### ISSUE THREAD

**Issue by gabebw** [teoljungberg/dotfiles#3]
Is `ripgrep` working well for you in general and as your `:grepprg`? Is it faster than `ag`?

**Comment by teoljungberg** [comment]
I moved over to `ripgrep` from `git grep`, and I didn't notice any major performance improvements. It _feels_ faster(which accounts for something) but I have not done any benchmarks to prove so.

What irked me about `ag` is the lack of compatibility with `grep(1)`, and it took some tweaking to `rg` for it to behave how I wanted it to. The `:grepprg` I ended up with, which now works how I want it to is:

```viml
set grepprg=rg\ --hidden\ --glob\ '!.git'\ --vimgrep\ --with-filename
set grepformat=%f:%l:%c:%m
```

I want my `:grep` to work with:
- Grepping for hidden files(let's be real, it's mostly dotfiles)
- Ignore `.git`, because there's rarely a use-case where I want to search inside of it. And when I do, I can always specify the full path and find what I please.
- I want to always display the filename I'm grepping for, meaning I can use `:grep some-token` aswell as `:grep some-token path/to/some/file` interchangeably.

Hope that helps!

**Comment by teoljungberg** [comment]
Also I love the idea of adding issues to ones dotfiles repository to keep track of things you want to look into / polish!

**Comment by gabebw** [comment]
I was super disappointed with ripgrep's speed vs ag, then I realized I had told ag to ignore lots of things (like image) so ripgrep was searching like 15% more files than ag.

I fixed it in [this commit](https://github.com/gabebw/dotfiles/commit/fb0dfc6308b8d1478e3da0ca2a6d54c3da8f79e5), which tells ripgrep to use [this file](https://github.com/gabebw/dotfiles/blob/master/searchignore) to find more things to ignore on top of the gitignore.

**Comment by teoljungberg** [comment]
Since `rg` ignores what's present in the `.gitignore` - I haven't needed to have another ignore file (yet).
